config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "foods#index"
  get '/users/:id/sign_out', to: 'application#sign_out_user', as: 'sign_out_user'
  
  resources :users
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods
  end
  resources :public_recipes

  put '/recipes/:id/toggle_public_status', to: 'recipes#toggle_public_status', as: 'toggle_public_status'
  get '/general_shopping_list/', to: 'shopping_list#index', as: 'shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, Recipe

    return unless user.present?

    can :manage, :all
    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, uniqueness: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy, foreign_key: :recipe_id
  has_many :foods, through: :recipe_foods
  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def toggle_public_status
    self.public = !public
    save
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, foreign_key: 'user_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :public_recipe?

  def sign_out_user
    sign_out current_user
    redirect_to root_path
  end

  def public_recipe?
    controller_name == 'public_recipes' && action_name == 'index'
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_user, only: %i[index new]

  def index
    @foods = Food.where(user_id: @user.id)
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      flash[:notice] = 'Food created successfully!'
      redirect_to foods_path(current_user)
    else
      flash[:alert] = "Couldn't create food!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])

    @food.destroy
    redirect_to foods_path, notice: 'Food successfully deleted.'
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user, :recipe_foods).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe

  def new
    @foods = Food.all
  end

  def create
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe)
      flash[:notice] = 'Recipe Food was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to recipe_recipe_foods_path(@recipe)
    flash[:notice] = 'Recipe Food was successfully deleted.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def recipe_food_params
    params.permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = current_user.recipes.includes(:user)
  end

  def show
    @recipe = Recipe.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render 'errors/not_found', status: :not_found
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def toggle_public_status
    @recipe = current_user.recipes.find(params[:id])
    @recipe.toggle_public_status

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
    flash[:notice] = 'Recipe was successfully deleted.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe_foods = RecipeFood.includes(recipe: :user, food: :user)
      .where(users: { id: current_user.id })
      .where('recipe_foods.quantity > foods.quantity')

    @total_food_items = @recipe_foods.sum { |item| item.quantity - item.food.quantity }
    @total_price = @recipe_foods.sum { |item| (item.quantity - item.food.quantity) * item.food.price }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    flash[:notice] = 'You are successfully logged in'
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<section class="foods-list">
  <h1>Food List</h1>
      <div class="btn-container">
    <button>
      <%= link_to 'Add Food',  new_food_path, class: "add-food-link" %>
    </button>
  </div>
  <table>
    <thead>
      <tr class="row-headings">
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price($)</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td><%= food.quantity%></td>
          <td><%= button_to 'Delete', food_path(food), method: :delete, onclick: "return confirm('Are you sure?')", class: "dlt-btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/foods/new.html.erb
<h2>Add new food</h2>
<%= form_with model: @food, url: foods_path, local: true, class: "food-form" do |f|%>
    <div>
        <%= f.label :name%><br>
        <%= f.text_field :name, required: true, placeholder: "Name", class: "food_name"%>
    </div><br>
     

    <div>
        <%= f.label :measurement_unit %><br>
        <%= f.text_field :measurement_unit, required: true, placeholder: "measurement_unit"%>
    </div><br>

    <div>
        <%= f.label :price %><br>
        <%= f.number_field :price, required: true, placeholder: "Price in $$$"%>
    </div><br> 

    <div>
        <%= f.label :quatity %><br>
        <%= f.text_field :quantity, required: true, placeholder: "Quantity"%>
    </div><br>

    <div>
        <%= f.submit "Create food", class: "submit-btn" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'public_toggle', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'index', "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "shared/nav"%>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
  <h2 class='public-recipe-heading'>Public Recipes</h2>
  <% @recipes.each do |recipe|%>
    <div>
            <%= link_to recipe_path(recipe.id), class: "public-recipe-card" do %>
                <div class="public-recipe">
                <div class="">
                    <h3 class=""><%= recipe.name %></h3>
                    <p class="">By: <%= recipe.user.name %></p>
                </div>
                    <article>
                        <p><strong>Total Food Items:</strong> <%= recipe.foods.count %></p>
                        <p><strong>Total Price:</strong> $<%= recipe.recipe_foods.sum { |rf| rf.food.price * rf.quantity } %></p>
                   </article>
                </div>
        <% end %>
    </div>
  <% end %>

app/views/recipe_foods/new.html.erb
<section>
  <div>
    <h2>Add Ingredient</h2>
    <%= form_with url: recipe_recipe_foods_path(@recipe), method: :post do |form| %>
      <div>
        <%= form.label :food_id, "Foods" %>
        <%= form.select :food_id, @foods.collect {|food| [food.name, food.id]}, { include_blank: false }, placeholder: "Foods" %>
      </div>
      <div>
        <%= form.label :quantity, "Quantity" %>
        <%= form.number_field :quantity, placeholder: "Quantity", class: 'number-field' %>
      </div>
      <div c>
        <%= form.submit "Add Food", class: 'submit-btn' %>
      </div>
    <% end %>
  </div>
</section>

app/views/recipes/_add_recipe.html.erb
<div class="form_container">
  <%= form_with model: @recipe, method: :post, local: true, class:'recipe-form' do |form| %>
    <div class="input_field">
      <%= form.label :name, "Recipe Name:" %>
      <%= form.text_field :name, required: true, placeholder: "Recipe name" %>
    </div>
    <div class="input_field">
      <%= form.label :preparation_time, "Preparation Time(hours):" %>
      <%= form.text_field :preparation_time, placeholder: "Preparation time", required: true%>
    </div>
    <div class="input_field">
      <%= form.label :cooking_time, "Cooking Time(hours):" %>
      <%= form.text_field :cooking_time, placeholder: "Cooking time", required: true%>
    </div>
    <div class="input_field">
      <%= form.label :description, "Recipe Description:" %>
      <%= form.text_area :description, required: true, placeholder: "Recipe Description"%>
    </div>
    <div>
      <%= form.submit "Add Recipe", class: 'submit-btn'%>
    </div>
  <% end %>
</div> 

app/views/recipes/_toggle_public_status.html.erb
<div>
    Public:
    <span class="toggle-btn <%=@recipe.public? ? 'public' : 'private'%>"
    onclick= 'togglePublicStatus()'>
      <% if @recipe.public? %>
        <%= button_to toggle_public_status_path(@recipe), class: 'toggle-btn-toggle public', method: :put, remote: true do%>
        <%end%>
      <% else %>
          <%= button_to toggle_public_status_path(@recipe), class: 'toggle-btn-toggle', method: :put, remote: true do%>
          <%end%>
      <% end %>
    </span>
</div>

app/views/recipes/index.html.erb
<h2>Recipes</h2>
<%= link_to 'Add Recipe', new_recipe_path, class:'add-recipe' %>

<% if @recipes.empty? %>
<p>No recipes added yet, click Add Recipe to add a new recipe</p>
<%else%>
<div>
  <ul class='recipes'>
  <%@recipes.each do |recipe|%>
    <li class='recipe-container'>
      <section class='recipe-card'>
        <div class='recipe-title'>
          <h2><%= link_to recipe.name, recipe_path(recipe), class:'recipe-heading' %></h2>

          <% if current_user == recipe.user %>
          <%= button_to 'Remove', recipe_path(recipe), method: :delete%>
          <% end %>
        </div>
        <p class='description'><%=recipe.description%></p>
      </section>
    </li>
    <%end%>
  </ul>
</div>
<%end%>

app/views/recipes/new.html.erb
<div>
  <h2> Add a new Recipe</h2>
</div>
<div class="recipe-form">
  <%= render "add_recipe" %>
</div> 

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>
<div class='recipe-details'>
  <div class='recipe-time'>
    <p>Preparation Time: <%= @recipe.preparation_time %> hours</p>
    <p>Cooking Time: <%= @recipe.cooking_time %> hours</p>
    <p>Steps go here...</p>
  </div>

  <% if can? :update, @recipe %>
    <%= render 'toggle_public_status' %>
  <%end%>
</div>

<div class='recipe-interactions'>
  <div>  
  <% if current_user == @recipe.user %>
    <button disabled>Generate shopping list</button>
    <button class='add-ingredient' ><%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe) %></button>
  <% end %>
  </div>
  <hr>
</div>

<% if current_user == @recipe.user || @recipe.public?%>

<% if @recipe.recipe_foods.empty? %>
  <p class="no-food">No ingredients added yet, use add ingredient
  to add ingredients
  </p>
<% else %>
<table border="1">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @recipe.recipe_foods.includes(:food).each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name%></td>
        <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
        <td>$<%= recipe_food.quantity * recipe_food.food.price %></td>
        <td>
          <% if can? :destroy, recipe_food %>
            <%= link_to 'Remove', recipe_recipe_food_path(@recipe.id, recipe_food.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, type:"button" %>
          <% end %>
        </td>
      </tr> 
    <% end %>
  </tbody>
</table>
<% end %>
<%end%>

app/views/shared/_nav.html.erb
<header>
    <nav>
        <ul class='nav-list'>
            <% if user_signed_in? %>
                <li><%= link_to 'Food list', foods_path%></li>
                <li><%= link_to 'Recipes', recipes_path%></li>
                <li><%= link_to 'Public Recipes', public_recipes_path%>
                <li><%= link_to 'General Shopping list', shopping_list_path %></li>
                <li><%= link_to 'Sign Out', sign_out_user_path(current_user.id), method: :delete %></li>
            <%end%>
        </ul>
    </nav>
</header>

app/views/shopping_list/index.html.erb
<h2>Shopping List</h2>

<div class="food-items-count">
  <p><strong>Amount of food items to buy:</strong> <%= @total_food_items %></p>
  <p><strong>Total value of food needed:</strong> <%= "$#{@total_price}" %></p>
</div>

<% if @recipe_foods.any? %>
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity - recipe_food.food.quantity %> <%=recipe_food.food.measurement_unit%></td>
          <td><%= "$#{(recipe_food.quantity - recipe_food.food.quantity) * recipe_food.food.price}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No missing foods for your recipes.</p>
<% end %>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>